import type { Metadata } from "next";
// import "./globals.css";
import { Navigation } from "../components";
import Footer from "../components/Footer";
import { viewport } from "./viewport";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="english">
      <head >
         <meta name="viewport" content={viewport}/>
      </head>
      <body className={"font-Inter-Regular"}>
      <Navigation />
     
        {children}
        <Footer />
        </body>
    </html>
  );
}
