import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "./_component/SideBar";
import Navbar from "./_component/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="english">
      <body>
        {/* Navigation */}
        <Navbar />

        {/* Main content */}
        <main className="lg:pl-[250px] pt-0 lg:pt-[12vh]">
          {children}
        </main>

      </body>
    </html>
  );
}
