import type { Metadata } from "next";
import { Inter } from "next/font/google";
<<<<<<< HEAD
import "../globals.css";
=======
import "../../app/globals.css";
>>>>>>> a4832cb1862850a8d6906f67c32a0a43a216f805

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="english">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
